
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Language;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int TK_concat = 17;
  public static final int TK_limit = 19;
  public static final int TK_tilde = 13;
  public static final int TK_char = 5;
  public static final int TK_comma = 11;
  public static final int TK_id = 3;
  public static final int TK_lbr = 7;
  public static final int TK_positive = 15;
  public static final int TK_str = 4;
  public static final int TK_prompt = 12;
  public static final int TK_singlequ = 20;
  public static final int TK_semicolon = 9;
  public static final int RW_CONJ = 2;
  public static final int EOF = 0;
  public static final int TK_optional = 18;
  public static final int TK_rbr = 8;
  public static final int TK_kleene = 16;
  public static final int error = 1;
  public static final int TK_doublequ = 21;
  public static final int TK_charnum = 6;
  public static final int TK_or = 14;
  public static final int TK_newline = 22;
  public static final int TK_colon = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RW_CONJ",
  "TK_id",
  "TK_str",
  "TK_char",
  "TK_charnum",
  "TK_lbr",
  "TK_rbr",
  "TK_semicolon",
  "TK_colon",
  "TK_comma",
  "TK_prompt",
  "TK_tilde",
  "TK_or",
  "TK_positive",
  "TK_kleene",
  "TK_concat",
  "TK_optional",
  "TK_limit",
  "TK_singlequ",
  "TK_doublequ",
  "TK_newline"
  };
}

